# Generated by Django 3.2.3 on 2021-06-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210604_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='usuario',
        ),
    ]
